### ISSUE TITLE
undefined symbol: DSpot_new

### ISSUE THREAD

**Issue by hari-packetai** [asiffer/libspot#2]
I have downloaded the repository and created the shared object file `libspot.so` by running `make` and `make install`. I also installed the python bindings by running `pip install pylibspot`. When I run a test script (based on the example given in the website), I get the following error:

Traceback (most recent call last):
  File "test_spot.py", line 10, in <module>
    import pylibspot as ps # name of the python3 package
  File "/home/hari/.local/lib/python3.8/site-packages/pylibspot.py", line 196, in <module>
    LIBSPOT.DSpot_new.argtypes = [c_int, c_double, c_int, c_double, c_bool, c_bool,
  File "/home/hari/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/home/hari/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/libspot.so: undefined symbol: DSpot_new

Based on the build steps, the class `DSpot_new` is expected to be present in `interface.o` and it is present in the corresponding source and header files. What could be going wrong?

The error happens when I use the shared object file in Snap, also.

Note: I am unable to `sudo apt install libspot libspot-dev` because my Ubuntu distribution is focal and I get a `Repository does not have a release file` error.

**Comment by asiffer** [comment]
Sorry for the huge delay, I did not see your issue. What is the status of the issue?

**Comment by hari-packetai** [comment]
I couldn't use libspot in Python. I did my experiments in C++.
